# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Opt

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Check opt.py
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Try cosmology.py
      run: |
        rm -f ./mu-z.png
        rm -f ./cost.png
        rm -f ./parameters.json
        python cosmology.py
    - name: Check mu-z.png
      run: test -e ./mu-z.png
    - name: Check cost.png
      run: test -e ./cost.png
    - name: Check parameters.json
      run: python ./.github/workflows/check.py ./parameters.json
    - name: Check names
      run: python ./.github/workflows/check2.py
